import = ["/Users/iveahugeship/.config/alacritty/window.toml", "/Users/iveahugeship/.config/alacritty/bindings.toml", "/Users/iveahugeship/.config/alacritty/fonts.toml", "/Users/iveahugeship/.config/alacritty/themes/default.toml"]
